version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_USER: unisphere
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: unisphere
      MARIADB_ROOT_PASSWORD: password
      MYSQL_TCP_PORT: 3306
      MYSQL_UNIX_PORT: 3306
    ports:
      - 3311:3306
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--silent",
          "-h",
          "localhost",
          "-u",
          "unisphere",
          "-ppassword",
        ]
      timeout: 20s
      retries: 10

  nginx:
    image: nginx:latest
    restart: always
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80

