AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SpringBoot on AWS Lambda Study

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        SPRING_PROFILES_ACTIVE: prod

Resources:
  SpringLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.unisphere.unisphere.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: .
      MemorySize: 2048
      Timeout: 60
      Architectures:
        - x86_64
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        SpringLambda:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY