name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:
  backend-CI:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: JDK 11 설정
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle 빌드
        run: |
          echo ${{ secrets.APPLICATION_LOCAL_YML }} | base64 -d > src/main/resources/application-local.yml
          echo ${{ secrets.APPLICATION_PROD_YML }} | base64 -d > src/main/resources/application-prod.yml
          chmod +x gradlew
          ./gradlew build
        shell: bash

      - name: SAM 설치
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: AWS SAM Build
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sam build --use-container --template template.yml

      - name: AWS Credentials 설정
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: AWS SAM Package
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sam package --template-file .aws-sam/build/template.yaml --output-template-file packaged.yml --s3-bucket ${{ secrets.S3_DEPLOY_BUCKET }}

      - name: AWS SAM Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sam deploy --template-file packaged.yml --stack-name ${{ secrets.STACK_NAME }} --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} --no-confirm-changeset --no-fail-on-empty-changeset